### ISSUE TITLE
Initiating a conversation

### ISSUE THREAD

**Issue by johngriffin** [krismuniz/botkit-sms#6]
I'm having trouble initiating a conversation. The botkit docs say that I should use bot.startPrivateConversation to do this but when I go I get:
`TypeError: bot.startPrivateConversation is not a function`

If I try to use startConversation instead, I get the initial question delivered, but my responses are not heard by `askQuestion`.  I've taken the following code verbatim from botkit docs, stripped the surrounding `controller.hears` (because I want to initiate the conversation), and passed in a dummy message:

```
var message = {
  "channel": '+xxxxxxxxxxxx',  // my phone number
  "text": ""
}

askFlavor = function(response, convo) {
  convo.ask('What flavor of pizza do you want?', function(response, convo) {
    convo.say('Awesome.');
    askSize(response, convo);
    convo.next();
  });
}
askSize = function(response, convo) {
  convo.ask('What size do you want?', function(response, convo) {
    convo.say('Ok.')
    askWhereDeliver(response, convo);
    convo.next();
  });
}
askWhereDeliver = function(response, convo) {
  convo.ask('So where do you want it delivered?', function(response, convo) {
    convo.say('Ok! Good bye.');
    convo.next();
  });
}

bot.startPrivateConversation(message, askFlavor);

```

**Comment by krismuniz** [comment]
The `.startPrivateConversation()` method is not defined for `botkit-sms` because all SMS conversations are 1:1 (i.e. private). `.startPrivateCoversation()` makes sense in Slack because you can have conversations inside channels or on private threads.

That said, I see why `.startConversation()` wouldn't work. `botkit-sms` internally routes messages to conversations by matching the property `user` instead of `channel` (my bad). So your mock message should look something like this instead:

```js
{
  text: '',
  user: '+WXXXYYYZZZZ' // your phone number
}
```

I never thought of that use case (i.e. starting a conversation from the bot) so I just made sure it worked internally. I'll change this as soon as I can, but in the meantime you can use both `user` and `channel` to make sure 😁

**Comment by krismuniz** [comment]
Please tell me if this fixes your issue. :)

**Comment by krismuniz** [comment]
I updated the package to match either `message.user` or `message.channel`.

**Comment by johngriffin** [comment]
Awesome, thanks @krismuniz - issue fixed!
